DROP TABLE IF EXISTS hits;

CREATE TABLE IF NOT EXISTS hits (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ip VARCHAR(100),
    uri VARCHAR(100),
    app VARCHAR(100),
    hit_time TIMESTAMP
);